### PR TITLE
PHP8.4 Support Added

### PR DESCRIPTION
**Pull request by cod43156**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Review by gsteel — CHANGES_REQUESTED** [review]
Thanks @cod43156 

Please wait for #58 to be merged and then rebase.

There are deprecations here on 8.4 with lowest deps that are not failing CI.

#58 will either fix these, or reveal any problems

**Comment by samsonasik** [comment]
@cod43156 please rebase

**Comment by cod43156** [comment]
> @cod43156 please rebase

@samsonasik rebased

**Review by gsteel — APPROVED** [review]
Thanks @cod43156 👍

**Pull request merged**
