### PR TITLE
[Doc Tutorial] Add missing , $priority = 1 parameter in example LogEvents::attach()

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| Documentation | yes

### CODE REVIEW

**Comment by froschdesign** [comment]
Reference:

https://github.com/laminas/laminas-eventmanager/blob/0cb5459480b539bdc330317170344564fdfe0ff8/src/ListenerAggregateInterface.php#L21-L31

**Review by froschdesign — APPROVED** [review]

**Comment by samsonasik** [comment]
@froschdesign do we need new release for this?

**Comment by froschdesign** [comment]
@samsonasik 
Yes. This was all discussed and defined in a TSC meeting. (And no, it wasn't my idea. 😉 )

**Comment by samsonasik** [comment]
@froschdesign thank you, merging it.

**Comment by froschdesign** [comment]
@samsonasik 
Btw. good catch! 👍

**Pull request merged**
